-- 游戏库
-- 角色表建表
CREATE TABLE `user` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色id, 1000W起',
	`account_id` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号id',
	`name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色名',
	`last_login` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最后一次登陆日期(YYYYMMDD)',
	`create_time` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间(utc时间)',
	`exit_time` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '退出时间(utc时间)',
	`yesterday_login` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '昨日登陆标记',
	`all_online_time` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总在线时间(单位秒)',
	`server_group` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '归属服务器组',
	`lev` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '等级',
	`exp` BIGINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验',
	`sex` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '性别',
	`lookface` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '头像',
	`del_flag` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '删除标记',
	`account_type` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号类型, 每次登陆从账号表覆盖过来',
	`max_score` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最大战斗力',
	`max_poker_star` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '卡牌总星级',
	`init_poker` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '初始化卡牌选择',
	`stop_talk_end_time` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '禁言结束时间(utc时间)',
	`exp0_date_days` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量0 EPOCH DAY',
	`exp0_date_ymd` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量0 YYYYMMDD',
	`exp0_date_value` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量0 经验值',
	`exp1_date_days` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量1 EPOCH DAY',
	`exp1_date_ymd` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量1 YYYYMMDD	',
	`exp1_date_value` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量1 经验值',
	`exp2_date_days` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量2 EPOCH DAY',
	`exp2_date_ymd` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量2 YYYYMMDD',
	`exp2_date_value` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '经验统计量2 经验值',
	`signature` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '个性签名',
	`lookface_frame` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '头像框',
	`birthday` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '出生日期 YYYYMMDD',
	`address` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所在地',
	`glamour` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '魅力值',
	`glamour_total` INT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '总魅力值',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `name` (`name`),
	INDEX `account_id` (`account_id`),
	INDEX `last_login` (`last_login`),
	INDEX `create_time` (`create_time`),
	INDEX `account_type` (`account_type`),
	INDEX `server_group` (`server_group`),
	INDEX `max_score` (`max_score`)
)
COMMENT='角色表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;